apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamefinder
  namespace: gamefinder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamefinder
  template:
    metadata:
      labels:
        app: gamefinder
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: secret-volume
        secret:
          secretName: gamefinder-env
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        volumeMounts:
        - name: nginx-conf
          readOnly: true
          mountPath: /etc/nginx
        ports:
        - containerPort: 80
          protocol: TCP
      - name: gamefinder
        image: ${CICD_IMAGE}:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: /var/www
        ports:
        - containerPort: 9000
          protocol: TCP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: gamefinder
data:
  nginx.conf: |
    server {
        listen 80;
        index index.php index.html;
        root /var/www/public;

        location / {
            try_files $uri /index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_buffers 16 16k; 
            fastcgi_buffer_size 32k;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }

---

apiVersion: v1
kind: Service
metadata:
  name: gamefinder-service
  namespace: gamefinder
spec:
  type: ClusterIP
  ports:
    - name: gamefinder-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: gamefinder

---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: gamefinder-ingress
  namespace: gamefinder
spec:
  rules:
    - host: gamefinder.guldentech.com
      http:
        paths:
          - path: /
            backend:
              serviceName: gamefinder-service
              servicePort: gamefinder-port
